// module.exports={
//     host:"localhost",
//     dialect:"mysql",
//     username:"root",
//     password:"root",
//     database:"cartracking",
//     define:{
//         timestamps:true,
//         underscored:true
//     }
// }
// module.exports={
//     host:"localhost",
//     dialect:"mssql",
//     username:"DESKTOP-P8J1R0C\duong",
//     password:"",
//     database:"TrackingVietin",
//     define:{
//         timestamps:true,
//         underscored:true
//     }
// }