module.exports={
    host:"localhost",
    dialect:"mysql",
    username:"root",
    password:"root",
    database:"cartracking",
    define:{
        timestamps:true,
        underscored:true
    }
}